import Head from 'next/head'
import Header from '../components/Layout/Header/Header'
import Footer from '../components/Layout/Footer/Footer'
import Main from '../components/Layout/Main/Main'

import React from 'react'

const index = () => {
  return (
    <>
      <Head>
      <title>우리 것</title>
      <meta name="description" content="Generated by create next app"/>
      </Head> 
      <Main />
      
    </>
  )
}

export default index
